---
- hosts: localhost
  collections: 
  - netapp.ontap
  gather_facts: false
  tasks:
  - name: Gather information from NetApp cluster
    na_ontap_info:
      state: info
      hostname: "{{ hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      desired_attributes: vserver_nfs_info
      https: true
      validate_certs: false
