---
- hosts: localhost
  name: NetApp licensing
  vars:
   login: &login
   hostname: 192.168.36.128
    username: admin
    password: "{{ passwordntap }}"
    https: true
    validate_certs: false
    clustername: petentap01
  tasks:
  - name: Install Licenses
    na_ontap_cluster:
      state: present
      cluster_name: "{{ clustername }}"
      license_code: "{{ item }}"
      <<: *login
   loop:
     - CAYHXPKBFDUFZGABGAAAAAAAAAAA
     - APTLYPKBFDUFZGABGAAAAAAAAAAA
     - WSKTAQKBFDUFZGABGAAAAAAAAAAA
     - CGVTEQKBFDUFZGABGAAAAAAAAAAA
     - OUVWXPKBFDUFZGABGAAAAAAAAAAA
     - QFATWPKBFDUFZGABGAAAAAAAAAAA
     - UHGXBQKBFDUFZGABGAAAAAAAAAAA
     - GCEMCQKBFDUFZGABGAAAAAAAAAAA
     - KYMEAQKBFDUFZGABGAAAAAAAAAAA
     - SWBBDQKBFDUFZGABGAAAAAAAAAAA
     - YDPPZPKBFDUFZGABGAAAAAAAAAAA
     - INIIBQKBFDUFZGABGAAAAAAAAAAA
